name = "MultiGridBarrier"
uuid = "9e2c1f1d-9131-4ad4-b32f-bd2a0b0ecd1e"
authors = ["SÃ©bastien Loisel"]
version = "0.11.20"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
QuadratureRules = "a08977f5-a20d-4b99-b11f-f5ea535e0575"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ForwardDiff = "0.10, 0.11, 1"
PrecompileTools = "1.2.1"
ProgressMeter = "1"
PyCall = "1"
PyPlot = "2.11.5"
QuadratureRules = "0.1"
julia = "1.10"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Coverage"]
